//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.PORTALADMINISTRADOR.WEB.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorizationn
    {
        public int AuthorizationId { get; set; }
        public int SapObjectType { get; set; }
        public int SapKey { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> AprovalTypeId { get; set; }
        public Nullable<int> MaxAprovalSubTypeId { get; set; }
        public Nullable<int> CurrentAprovalSubTypeId { get; set; }
        public Nullable<int> NextAprovalSubTypeId { get; set; }
    
        public virtual AprovalSubType AprovalSubType { get; set; }
        public virtual AprovalSubType AprovalSubType1 { get; set; }
        public virtual AprovalSubType AprovalSubType2 { get; set; }
        public virtual AprovalType AprovalType { get; set; }
    }
}
