//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.PORTALADMINISTRADOR.WEB.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SAPAUTHORIZATIONEntities : DbContext
    {
        public DB_SAPAUTHORIZATIONEntities()
            : base("name=DB_SAPAUTHORIZATIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AprovalSubType> AprovalSubType { get; set; }
        public virtual DbSet<AprovalType> AprovalType { get; set; }
        public virtual DbSet<Authorizationn> Authorizationn { get; set; }
        public virtual DbSet<AuthorizationnHistory> AuthorizationnHistory { get; set; }
        public virtual DbSet<CONFIG> CONFIG { get; set; }
        public virtual DbSet<GrupoVista> GrupoVista { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SapUsersPerAprovalTypeLevel> SapUsersPerAprovalTypeLevel { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRoles> UsuarioRoles { get; set; }
        public virtual DbSet<Vista> Vista { get; set; }
        public virtual DbSet<VistaRol> VistaRol { get; set; }
    }
}
