//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.PORTALADMINISTRADOR.WEB.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRol
    {
        public int VistaRolId { get; set; }
        public bool Estado { get; set; }
        public int VistaId { get; set; }
        public int RolId { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Vista Vista { get; set; }
    }
}
