//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONEPAR.PORTALADMINISTRADOR.WEB.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vista()
        {
            this.VistaRol = new HashSet<VistaRol>();
        }
    
        public int VistaId { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int GrupoVistaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VistaRol> VistaRol { get; set; }
    }
}
